### ISSUE TITLE
Crash when Mechanical User tries to trade with Player

### ISSUE THREAD

**Issue by Kamefrede** [AeronicaMC/mxTune#1]
When a Mechanical User is set to interact with an entity with right click and if a player approaches it   sends a message to the chat saying that the Mechanical User wants to trade with the player but then crashes. 
I'm unsure if this also occurs with other fake players.

Crash report:
https://pastebin.com/3yrRuVdS

PS: Could we get an option to disable the trade feature?

**Comment by Aeronica** [comment]
Hi and thank you for the report. I may have fixed this, but I have not yet released a new version for a while. I will also add an option to disable the mxTune JAM (Party) feature.

**Comment by Aeronica** [comment]
Adding a General Option for this. I'll release later today.
![image](https://user-images.githubusercontent.com/6465667/59304689-5d33c880-8c5e-11e9-804f-29eb7109c846.png)

**Comment by Aeronica** [comment]
Released mxtune-1.12.2-0.7.0-beta.5.jar on CurseForge.
