### ISSUE TITLE
NullPointerException in Jam Overlay

### ISSUE THREAD

**Issue by AhiVT** [AeronicaMC/mxTune#3]
https://paste.dimdev.org/doqenecabe.mccrash
version is `0.7.0-beta.6`

**Comment by Aeronica** [comment]
Hi, thank you for the crash report.
I assume you had an mxTune instrument equipped.
What were you doing at the time of the crash?
Can you send the mxTune config files that are in use please?

Regards,
-Aero

**Comment by AhiVT** [comment]
[mxtune_general.cfg](https://gist.github.com/Kexerval/df8f4d95d26b27305d0131aad4e698df)
[mxtune_client.cfg](https://gist.github.com/Kexerval/52840711b526f5efc4251a40bc4227c1)
[mxtune_recipes.cfg](https://gist.github.com/Kexerval/8b94d5f26ddeccd30dfe459c48775c3a)
1) I joined a party of 2
2) We start, but cancel playback of a few songs.
3) While not playing a song, I switch active hotbar position. Moments later (but not instantly) I crash, along with my other party members (one after another, not all at once).

**Comment by Aeronica** [comment]
Thank your for the scenario and config files.
I can see the mod pack is fairly large. Is this  personal mod pack, or one from CurseForge/FTB or Technic?  If you have a link I'd appreciate it. Might be easier for me to reproduce if I simulate the same environment. 

Is the mod-pack running from a dedicated remote or local server, or is it running in LAN mode?

Sorry for the extra questions. I have not setup templates for this issue tracker yet,

Regards,
-Aero

**Comment by Aeronica** [comment]
Add/Correct checks for null pointers to general group classes. Release new mod jar on CurseForge.

2019-09-15 mxtune-1.12.2-0.7.0-beta.7
Fixes:
 * GitHub #3: NullPointerException in Jam Overlay: java.lang.NullPointerException
   at net.aeronica.mods.mxtune.gui.hud.GuiJamOverlay.processGroup(GuiJamOverlay.java:258)
   Properly check for null entity when using World#getEntityByID.
