### ISSUE TITLE
1.7.10

### ISSUE THREAD

**Issue by zxterProxy** [AeronicaMC/mxTune#4]
Hi. I really respect you for your work. Is it possible to get outdated code on 1.7.10?

**Comment by Aeronica** [comment]
There are no plans to allocate time to the [mcJammer 1.7.10 ](https://github.com/Aeronica/MCJammer-1.7.10) version.
Current work priorities are to re-write the MML parser. Then add a new player managed music player item/block for use in player instances/dimensions for popular Modded MC server. After that build a release candidate for 1,12.2 mcTune version. Then begin work on a 1.16.x port.
