### ISSUE TITLE
[Small Suggestion 1.12] Add a config option to remove mxtune mob spawns

### ISSUE THREAD

**Issue by jawsawn** [AeronicaMC/mxTune#6]
Hey I recently tried to make a modpack with mxtune but the mob spawning not having a config turned me away. 
I wouldn't care about this a week ago but since it's going to be updated due to the current java issue, I wanted to suggest adding a line of config to disable mob spawning for the 1.12 version.

**Comment by Aeronica** [comment]
Will do. No ETA on the java issue fix yet. I don't code much over the summer.

**Comment by Aeronica** [comment]
2023-10-31 mxtune-1.12.2-1.1.0

 * Fix the Unsafe Network Deserialization Vulnerability.
 * Remove chunk/world music system. Chunk Tool and Staff of Music items removed. Forge will prompt you to back up the save files
 * Minor enhancement: Sheet Music GUI *Make Sheet Music* button now disabled when not enough sheets in the stack.
* **_[Add options to disable mxTune mobs.](https://www.curseforge.com/minecraft/mc-mods/mxtune/files/4830677)_**
