### ISSUE TITLE
crash single player

### ISSUE THREAD

**Issue by ghost** [AeronicaMC/mxTune#7]
logs: 
[latest.log](https://github.com/AeronicaMC/mxTune/files/13514111/latest.log)

**Comment by Aeronica** [comment]
There is no log. Use a text dump site or a github gist to share the log please.

**Comment by ghost** [comment]
like this? https://pastebin.com/sn6fD9dz

**Comment by Aeronica** [comment]
Yes, pastebin.com is prefect. 
1. What mod-pack are you running?
2. When does this fail. For example while loading mods before entering the world, during normal game play, etc.

**Comment by ghost** [comment]
> Yes, pastebin.com is prefect.
> 
>     1. What mod-pack are you running?
> 
>     2. When does this fail. For example while loading mods before entering the world, during normal game play, etc.

I use my modpack on 1.16.5. The error happens when loading into the world

**Comment by ghost** [comment]
the list of mods is at the end of the log

**Comment by Aeronica** [comment]
This could be caused a mod/mixin conflict. I'm seeing mixin class loading issues in render pipeline. Have you tried a binary chop mod removal? That is removing half of the mods at a time on a backup of the world until it works.

**Comment by Aeronica** [comment]
Upon reviewing my code, I will make some optimizations and sanity checks. I should have a new release some time this weekend.

**Comment by Aeronica** [comment]
Posted to CurseForge https://www.curseforge.com/minecraft/mc-mods/mxtune/files/4946141
2023-12-10 mxtune-1.16.5-2.0.0-beta-2023-12-08.76721460
Please let me know if the world loads properly now.
